version: '3.2'

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
      - LOG_LEVEL=DEBUG
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainerci/portainer:2.17.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify --log-level DEBUG
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    environment:
      - UPGRADE_SKIP_PULL_PORTAINER_IMAGE=true
      - UPGRADE_UPDATER_IMAGE=portainerci/portainer-updater:pr6
      - UPGRADE_PORTAINER_IMAGE_PREFIX=portainerci/portainer-ee
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_swarm_update:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data_swarm_update:
