$install_docker_script = <<SCRIPT
echo "Installing dependencies ..."
DEBIAN_FRONTEND=noninteractive sudo apt-get update
echo "Installing Docker..."
curl -sSL https://get.docker.com/ | sh

sudo usermod -aG docker vagrant;

sed -i 's|-H fd://|-H fd:// -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock|g' /lib/systemd/system/docker.service;
systemctl daemon-reload && systemctl restart docker.service;
SCRIPT

BOX_NAME = "ubuntu/bionic64"
MEMORY = "512"
CPUS = 2
MANAGERS = ENV['SWARM_MANAGERS'] || 1
MANAGER_IP = "192.168.56.10"
WORKERS = ENV['SWARM_WORKERS'] || 1
WORKER_IP = "192.168.56.11"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #Common setup
  config.vm.box = BOX_NAME
  
  config.vm.provision "shell", inline: $install_docker_script, privileged: true
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  (1..MANAGERS).each do |i|
    config.vm.define "manager0#{i}" do |manager|
      manager.vm.network :private_network, ip: "#{MANAGER_IP}#{i}"
      manager.vm.hostname = "manager0#{i}"
    end
  end

  (1..WORKERS).each do |i|
      config.vm.define "worker0#{i}" do |worker|
          worker.vm.network :private_network, ip: "#{WORKER_IP}#{i}"
          worker.vm.hostname = "worker0#{i}"
      end
  end
end
