$setup_docker = <<SCRIPT
echo "Installing dependencies ..."
DEBIAN_FRONTEND=noninteractive sudo apt-get update
echo "Installing Docker..."
curl -sSL https://get.docker.com/ | sh

sudo usermod -aG docker vagrant;

sed -i 's|-H fd://|-H fd:// -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock|g' /lib/systemd/system/docker.service;
systemctl daemon-reload && systemctl restart docker.service;
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "standalone" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "swarmnode1"
    config.vm.network "private_network", ip: "192.168.56.20"
    config.vm.provision "shell", inline: $setup_docker
  end
end
